name: "Release"
on:
  workflow_call:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        type: string
      snapshotVersion:
        description: 'Snapshot version'
        required: true
        type: string
      javaVersion:
        description: 'Version of Java to release with'
        required: true
        type: string
jobs:
  Prepare:
    runs-on: ubuntu-latest
    env:
      # Needed by actions/setup-java
      MAVEN_GPG_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    steps:
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: |
            8
            11
            17
            21
          distribution: temurin
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$JAVA_HOME_${{ inputs.javaVersion }}_X64" >> $GITHUB_ENV
      - name: Configure Maven settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          githubServer: false
          servers: |
            [{
              "id": "central",
               "username": "${{ secrets.CENTRAL_USERNAME }}",
               "password": "${{ secrets.CENTRAL_PASSWORD }}"
            },{
              "id": "vertx-snapshots-repository",
               "username": "${{ secrets.CENTRAL_USERNAME }}",
               "password": "${{ secrets.CENTRAL_PASSWORD }}"
            }]
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.releaseVersion }}
      - name: Configure git
        run: |
          git config --global user.name "Julien Viet"
          git config --global user.email "julien@julienviet.com"
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Clone
        run: |
          chmod +x ./clone.sh
          ./clone.sh
      - name: Set release version
        run: mvn versions:set -DnewVersion=${{ inputs.releaseVersion }} -DoldVersion=* -DgroupId=* -DartifactId=* -DgenerateBackupPoms=false -DprocessDependencies=false
      - name: Commit release version
        run: mvn -B com.julienviet:releaser-maven-plugin:commit
      - name: Tag release version
        run: mvn -B com.julienviet:releaser-maven-plugin:tag
      - name: Deploy release to Sonatype Central
        run: mvn -B -T 4 -Prelease -DskipTests -Dgpg.signer=bc clean deploy
      - name: Set snapshot version
        run: mvn versions:set -DnewVersion=${{ inputs.snapshotVersion }} -DoldVersion=* -DgroupId=* -DartifactId=* -DgenerateBackupPoms=false -DprocessDependencies=false
      - name: Commit snapshot version
        run: mvn -B com.julienviet:releaser-maven-plugin:commit -DcommitMessage="Set next snapshot version"
      - name: Deploy snapshot to Sonatype Central
        run: mvn -B -T 4 -DskipTests clean deploy
      - name: Attach artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          compression-level: 9
          include-hidden-files: true
          path: |
            clone.sh
            push.sh
            pom.xml
            modules
            !modules/**/target